version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7861:7860"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
